### ISSUE TITLE
Super Micro series engines

### ISSUE THREAD

**Issue by stevexyz** [leanchess/leanchess#2]
Seems it's not anymore the smallest, but in the story at https://leanchess.github.io/ you forgot to mention the Super Micro series! :)

Here's the link in case http://smmax.sourceforge.net/

PS: The field is getting populated! It would be nice to organize some tournaments with those sub-1K implementations!

And compliments for the extreme size!!!

**Comment by dmitry-shechtman** [comment]
LeanChess is 292 bytes short. How come that's not the smallest?

**Comment by stevexyz** [comment]
Super Micro WAS the smallest, I was just pointing that was missing in the history (it was released just after boot chess and was the smallest at that time) :)

Anyway seems to me that within the fide category (with en passant, castling and underpromotion) Super Micro might still be the smallest, or I missed some engine?

**Comment by dmitry-shechtman** [comment]
You are probably right. Unfortunately I don't see how I can fit it neatly in the LeanChess story. As for FIDE chess, I believe Atomchess is still the smallest, but I might be wrong.

**Comment by stevexyz** [comment]
From what I could read Atom chess ("Toledo Atomchess Reloaded plays full chess movements and currently sizes up to 779 bytes. It hasn't been optimized further
because of lack of time") is still very far from the Super Micro 583 bytes that in this category seems still holds the world record title...
Personally I think it's worth to be mentioned!
